### ISSUE TITLE
[DOC] spatial_join.quadtree_point_in_polygon results are flipped

### ISSUE THREAD

**Issue by khoaxtru20** [rapidsai/cuspatial#304] opened 2020-10-07 23:31 UTC
## Report incorrect documentation

**Location of incorrect documentation**
Provide links and line numbers if applicable.

https://docs.rapids.ai/api/cuspatial/stable/api.html?highlight=result#cuspatial.core.spatial_join.quadtree_point_in_polygon

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

I believe the documentation is correct, but the actual result from the function has the columns reversed (the `point_offset` column holds the `poly_offset` data and vice versa)

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

For example, I have this line here:

`key_to_point.iloc[sjoineddf['point_index']]`

Which is supposed to use the `point_index` column from the result of `quadtree_point_in_polygon` to index the keys from the result of `quadtree_on_points` so that I can index the actual points from my data.

As it is currently, the `point_index` has the same range as the total amount of polygons, while `polygon_index` has the same range as the total amount of points. So the above code actually has unintended results. However, switching out `point_index` with `polygon_index` gets exactly what I need, which tells me that the results are good, but the labeling of those columns is incorrect.

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

Rename the columns in the result of `quadtree_point_in_polygon` so that the data aligns with what is in the documentation (which is already correct).

**Comment by harrism** [comment] 2020-10-08 03:00
@zhangjianting @trxcllnt can you verify this? Should be easy fix.

**Comment by trxcllnt** [comment] 2020-10-09 06:43
I believe this is a duplicate of #284 which was closed in #291.

**Comment by harrism** [comment] 2020-10-12 04:50
Ahhh, thanks @trxcllnt . @khoaxtru20 as you can see [here](https://docs.rapids.ai/api/cuspatial/nightly/api.html?highlight=result#cuspatial.quadtree_point_in_polygon) in the docs for v0.16 (which will be released in the next week or so), this is fixed. Closing.

**Closed by harrism** 2020-10-12 04:50 UTC
Labels: ? - Needs Triage, doc
