### ISSUE TITLE
Conda installation fails in macOS

### ISSUE THREAD

**Issue by dheerajchand** [rapidsai/cuspatial#306] opened 2020-10-08 01:26 UTC
**Describe the bug**
Following the written instructions fails.

**Steps/Code to reproduce bug**
```

 ~  conda install -c rapidsai -c nvidia -c numba -c conda-forge \                      1 ↵  944  20:27:12
    cudf=0.13 python=3.6 cudatoolkit=10.2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=10.2
  - cudf=0.13

Current channels:

  - https://conda.anaconda.org/rapidsai/osx-64
  - https://conda.anaconda.org/rapidsai/noarch
  - https://conda.anaconda.org/nvidia/osx-64
  - https://conda.anaconda.org/nvidia/noarch
  - https://conda.anaconda.org/numba/osx-64
  - https://conda.anaconda.org/numba/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.```

**Expected behavior**

 I expected the instructions to work.


**Environment details (please complete the following information):**
 macOS Catalina 10.15.6
 

**Additional context**
Add any other context about the problem here.

**Comment by harrism** [comment] 2020-10-08 03:02
Closing as duplicate of #305.

**Closed by harrism** 2020-10-08 03:02 UTC
Labels: bug, duplicate
